[build]
  functions = "netlify/functions"  # Carpeta donde están tus funciones serverless
  node_version = "16"

[functions]
  node_bundler = "esbuild"  # Netlify usa esbuild para empaquetar las funciones