export const casasMatricesDemo = [
  {
    id: 'CM-ALBATROS',
    imagen: 'demo-albatros.png',
    rut: '76.483.210-1',
    razonSocial: 'Albatros Retail Group',
    encargadoGeneral: 'Valeria Pinto',
    telefonoEncargado: 962102334,
    correo: 'valeria.pinto@albatrosretail.com',
    banco: 'Banco Estado',
    tipoCuentaBancaria: 'Cuenta Corriente',
    numeroCuentaBancaria: '110-345678-3',
    titularCuenta: 'Albatros Retail Group',
    rutTitularCuenta: '76.483.210-1',
    correoNotificacionPago: 'pagos@albatrosretail.com',
    visitasMensuales: 2,
    visitasEmergenciaAnuales: 4,
    servicios: [
      { nombre: 'Mantención preventiva integral', frecuencia: 'Mensual', cobertura: 'RM y V Región' },
      { nombre: 'Soporte remoto 24/7', frecuencia: 'Continuo', cobertura: 'Nacional' },
    ],
    esLead: false,
  },
  {
    id: 'CM-SOLARIS',
    imagen: 'demo-solaris.png',
    rut: '65.118.309-6',
    razonSocial: 'Colegio Solaris',
    encargadoGeneral: 'Hernán Muñoz',
    telefonoEncargado: 974556610,
    correo: 'hmunoz@colegiosolaris.cl',
    banco: 'Banco de Chile',
    tipoCuentaBancaria: 'Cuenta Vista',
    numeroCuentaBancaria: '00-987654-1',
    titularCuenta: 'Corporación Educacional Solaris',
    rutTitularCuenta: '65.118.309-6',
    correoNotificacionPago: 'finanzas@colegiosolaris.cl',
    visitasMensuales: 1,
    visitasEmergenciaAnuales: 2,
    servicios: [
      { nombre: 'Operación laboratorio de computación', frecuencia: 'Quincenal', cobertura: 'Santiago' },
      { nombre: 'Capacitación docente en tecnología', frecuencia: 'Trimestral', cobertura: 'Remoto' },
    ],
    esLead: false,
  },
  {
    id: 'CM-NEBULA',
    imagen: 'demo-nebula.png',
    rut: '77.902.144-7',
    razonSocial: 'Nebula Labs SPA',
    encargadoGeneral: 'Ignacio Cifuentes',
    telefonoEncargado: 961104422,
    correo: 'ignacio@nebulalabs.io',
    banco: 'Scotiabank',
    tipoCuentaBancaria: 'Cuenta Corriente',
    numeroCuentaBancaria: '321-554433-6',
    titularCuenta: 'Nebula Labs SPA',
    rutTitularCuenta: '77.902.144-7',
    correoNotificacionPago: 'finance@nebulalabs.io',
    visitasMensuales: 3,
    visitasEmergenciaAnuales: 6,
    servicios: [
      { nombre: 'Mesa de ayuda para cowork', frecuencia: '24/7', cobertura: 'Nacional' },
      { nombre: 'Arriendo de equipos para startups', frecuencia: 'Mensual', cobertura: 'Nacional' },
    ],
    esLead: true,
  },
];

export const sucursalesDemo = [
  {
    id: 'SUC-ALB-PROV',
    casaMatrizId: 'CM-ALBATROS',
    estadoNombre: 'Operativa',
    encargadoSucursal: 'Héctor Yáñez',
    correoSucursal: 'hyanez@albatrosretail.com',
    telefonoSucursal: 227118841,
    sucursal: 'Albatros - Providencia',
    direccion: 'Av. Nueva Providencia 1234, Providencia',
  },
  {
    id: 'SUC-ALB-MAIP',
    casaMatrizId: 'CM-ALBATROS',
    estadoNombre: 'Con observaciones',
    encargadoSucursal: 'Sara Troncoso',
    correoSucursal: 'stroncoso@albatrosretail.com',
    telefonoSucursal: 228004422,
    sucursal: 'Albatros - Maipú',
    direccion: 'Av. Pajaritos 4567, Maipú',
  },
  {
    id: 'SUC-SOL-LOE',
    casaMatrizId: 'CM-SOLARIS',
    estadoNombre: 'Operativa',
    encargadoSucursal: 'Cecilia Vargas',
    correoSucursal: 'cvargas@colegiosolaris.cl',
    telefonoSucursal: 229876543,
    sucursal: 'Solaris - Lo Espejo',
    direccion: 'Los Olmos 224, Lo Espejo',
  },
  {
    id: 'SUC-SOL-MACU',
    casaMatrizId: 'CM-SOLARIS',
    estadoNombre: 'Suspendida temporalmente',
    encargadoSucursal: 'Juan Salvador',
    correoSucursal: 'jsalvador@colegiosolaris.cl',
    telefonoSucursal: 229871100,
    sucursal: 'Solaris - Macul',
    direccion: 'Av. Macul 1123, Macul',
  },
  {
    id: 'SUC-NEB-LAS',
    casaMatrizId: 'CM-NEBULA',
    estadoNombre: 'Operativa',
    encargadoSucursal: 'Camila Arévalo',
    correoSucursal: 'camila@nebulalabs.io',
    telefonoSucursal: 227000222,
    sucursal: 'Nebula Labs - Las Condes',
    direccion: 'Isidora Goyenechea 2800, Las Condes',
  },
  {
    id: 'SUC-NEB-VALP',
    casaMatrizId: 'CM-NEBULA',
    estadoNombre: 'Con observaciones',
    encargadoSucursal: 'Marco Barraza',
    correoSucursal: 'mbarraza@nebulalabs.io',
    telefonoSucursal: 322200567,
    sucursal: 'Nebula Labs - Valparaíso',
    direccion: 'Errázuriz 545, Valparaíso',
  },
];

export const cuentasDemo = [
  {
    name: 'Catalina Fuentes',
    telefono: 989002211,
    email: 'admin.demo@siroe.cl',
    password: 'Demo123*',
    tipoCuenta: 'Administrador',
    estadoCuenta: 'Activa',
    esTecnico: false,
    haveTickets: true,
  },
  {
    name: 'Mesa Ayuda Demo',
    telefono: 978001122,
    email: 'mesa.demo@siroe.cl',
    password: 'Demo123*',
    tipoCuenta: 'Mesa de Ayuda',
    estadoCuenta: 'Activa',
    esTecnico: false,
    haveTickets: true,
  },
  {
    name: 'Rodrigo Cárdenas',
    telefono: 976660011,
    email: 'rcardenas@siroe.cl',
    password: 'Demo123*',
    tipoCuenta: 'Técnico',
    estadoCuenta: 'Activa',
    esTecnico: true,
    haveTickets: false,
  },
  {
    name: 'Paula Donoso',
    telefono: 975500321,
    email: 'pdonoso@siroe.cl',
    password: 'Demo123*',
    tipoCuenta: 'Técnico',
    estadoCuenta: 'Activa',
    esTecnico: true,
    haveTickets: false,
  },
  {
    name: 'Francisca Beltrán',
    telefono: 962220098,
    email: 'comercial.demo@siroe.cl',
    password: 'Demo123*',
    tipoCuenta: 'Comercial',
    estadoCuenta: 'Activa',
    esTecnico: false,
    haveTickets: false,
  },
  {
    name: 'Leonardo Pizarro',
    telefono: 963330876,
    email: 'cliente.albatros@siroe.cl',
    password: 'Demo123*',
    tipoCuenta: 'Cliente',
    estadoCuenta: 'Activa',
    esTecnico: false,
    haveTickets: false,
  },
  {
    name: 'María Contreras',
    telefono: 963330654,
    email: 'cliente.solaris@siroe.cl',
    password: 'Demo123*',
    tipoCuenta: 'Cliente',
    estadoCuenta: 'Activa',
    esTecnico: false,
    haveTickets: false,
  },
];

export const cuentaCasaMatrizDemo = [
  { email: 'comercial.demo@siroe.cl', casaMatrizId: 'CM-ALBATROS' },
  { email: 'comercial.demo@siroe.cl', casaMatrizId: 'CM-SOLARIS' },
  { email: 'comercial.demo@siroe.cl', casaMatrizId: 'CM-NEBULA' },
  { email: 'cliente.albatros@siroe.cl', casaMatrizId: 'CM-ALBATROS' },
  { email: 'cliente.solaris@siroe.cl', casaMatrizId: 'CM-SOLARIS' },
];

export const equiposDemo = [
  {
    numeroSecuencial: 1,
    codigoId: 'ALB-NT-001',
    estado: 'Operativo',
    tipoEquipo: 'Notebook',
    casaMatrizId: 'CM-ALBATROS',
    sucursalId: 'SUC-ALB-PROV',
    departamento: 'Ventas Terreno',
    usuario: 'Laura Rivas',
    marca: 'Dell',
    modelo: 'Latitude 7440',
    numeroSerie: 'ALBNT001',
    procesador: 'Intel Core i7 13th',
    velocidadProcesador: '2.8 GHz',
    ram: 16,
    tipoAlmacenamiento: 'SSD',
    cantidadAlmacenamiento: 512,
    sistemaOperativo: 'Windows 11',
    ofimatica: 'Microsoft 365',
    antivirus: 'Defender for Business',
    esArriendo: false,
  },
  {
    numeroSecuencial: 2,
    codigoId: 'ALB-NT-002',
    estado: 'Requiere atención',
    tipoEquipo: 'All in One',
    casaMatrizId: 'CM-ALBATROS',
    sucursalId: 'SUC-ALB-PROV',
    departamento: 'Finanzas',
    usuario: 'Diego Véliz',
    marca: 'HP',
    modelo: 'EliteOne 870',
    numeroSerie: 'ALBAO002',
    procesador: 'Intel Core i5 12th',
    velocidadProcesador: '2.4 GHz',
    ram: 8,
    tipoAlmacenamiento: 'SSD',
    cantidadAlmacenamiento: 256,
    sistemaOperativo: 'Windows 11',
    ofimatica: 'Microsoft 365',
    antivirus: 'Eset Endpoint',
    esArriendo: false,
  },
  {
    numeroSecuencial: 3,
    codigoId: 'ALB-NT-003',
    estado: 'Operativo',
    tipoEquipo: 'Tablet',
    casaMatrizId: 'CM-ALBATROS',
    sucursalId: 'SUC-ALB-MAIP',
    departamento: 'Operaciones',
    usuario: 'Equipo de inventario',
    marca: 'Samsung',
    modelo: 'Galaxy Tab Active4',
    numeroSerie: 'ALBTB003',
    procesador: 'Snapdragon 778G',
    velocidadProcesador: '2.4 GHz',
    ram: 6,
    tipoAlmacenamiento: 'SSD',
    cantidadAlmacenamiento: 128,
    sistemaOperativo: 'Android 13',
    ofimatica: 'Google Workspace',
    antivirus: 'Lookout',
    esArriendo: true,
  },
  {
    numeroSecuencial: 1,
    codigoId: 'SOL-NT-001',
    estado: 'Operativo',
    tipoEquipo: 'Notebook',
    casaMatrizId: 'CM-SOLARIS',
    sucursalId: 'SUC-SOL-LOE',
    departamento: 'Coordinación Académica',
    usuario: 'Marcela Vera',
    marca: 'Lenovo',
    modelo: 'ThinkPad L14',
    numeroSerie: 'SOLNT001',
    procesador: 'Intel Core i5 11th',
    velocidadProcesador: '2.5 GHz',
    ram: 16,
    tipoAlmacenamiento: 'SSD',
    cantidadAlmacenamiento: 512,
    sistemaOperativo: 'Windows 11',
    ofimatica: 'Microsoft 365',
    antivirus: 'Kaspersky',
    esArriendo: false,
  },
  {
    numeroSecuencial: 2,
    codigoId: 'SOL-DS-002',
    estado: 'Requiere atención',
    tipoEquipo: 'Data Show',
    casaMatrizId: 'CM-SOLARIS',
    sucursalId: 'SUC-SOL-MACU',
    departamento: 'Aulas',
    usuario: 'Sala 3B',
    marca: 'Epson',
    modelo: 'PowerLite X49',
    numeroSerie: 'SOLDM002',
    procesador: 'N/A',
    velocidadProcesador: null,
    ram: null,
    tipoAlmacenamiento: 'Otro',
    cantidadAlmacenamiento: 0,
    sistemaOperativo: 'Firmware Epson',
    ofimatica: 'N/A',
    antivirus: 'N/A',
    esArriendo: false,
  },
  {
    numeroSecuencial: 3,
    codigoId: 'SOL-PC-003',
    estado: 'Operativo',
    tipoEquipo: 'Ordenador de Escritorio',
    casaMatrizId: 'CM-SOLARIS',
    sucursalId: 'SUC-SOL-LOE',
    departamento: 'Laboratorio Computación',
    usuario: 'Equipo 12',
    marca: 'Aukeytech',
    modelo: 'LabStation 300',
    numeroSerie: 'SOLPC003',
    procesador: 'AMD Ryzen 5 5600G',
    velocidadProcesador: '3.9 GHz',
    ram: 16,
    tipoAlmacenamiento: 'SSD',
    cantidadAlmacenamiento: 512,
    sistemaOperativo: 'Windows 11',
    ofimatica: 'Microsoft 365',
    antivirus: 'Sophos',
    esArriendo: false,
  },
  {
    numeroSecuencial: 1,
    codigoId: 'NEB-NT-001',
    estado: 'Operativo',
    tipoEquipo: 'Notebook',
    casaMatrizId: 'CM-NEBULA',
    sucursalId: 'SUC-NEB-LAS',
    departamento: 'Customer Success',
    usuario: 'Equipo onboarding',
    marca: 'Apple',
    modelo: 'MacBook Air M3',
    numeroSerie: 'NEBNT001',
    procesador: 'Apple M3',
    velocidadProcesador: '3.2 GHz',
    ram: 16,
    tipoAlmacenamiento: 'SSD',
    cantidadAlmacenamiento: 512,
    sistemaOperativo: 'macOS Sequoia',
    ofimatica: 'Google Workspace',
    antivirus: 'Jamf Protect',
    esArriendo: false,
  },
  {
    numeroSecuencial: 2,
    codigoId: 'NEB-SA-002',
    estado: 'No funcional',
    tipoEquipo: 'Sistema de Audio',
    casaMatrizId: 'CM-NEBULA',
    sucursalId: 'SUC-NEB-VALP',
    departamento: 'Eventos',
    usuario: 'Auditorio Principal',
    marca: 'Yamaha',
    modelo: 'Stagepas 1K',
    numeroSerie: 'NEBSA002',
    procesador: 'DSP Yamaha',
    velocidadProcesador: null,
    ram: null,
    tipoAlmacenamiento: 'Otro',
    cantidadAlmacenamiento: 0,
    sistemaOperativo: 'Firmware Yamaha',
    ofimatica: 'N/A',
    antivirus: 'N/A',
    esArriendo: true,
  },
];
